spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000
  jms:
    pub-sub-domain: false

